### ISSUE TITLE
perfmode works for keyboard backlight, but not for fan control

### ISSUE THREAD

**Issue by shdw** [icebarf/perfmode#6]
Hi there,

First, thanks for creating this tool. I've just compiled it, and it works great for the keyboard, but will error out as follows for any fan setting :

```
gen2rog /code/perfmode # ./perfmode -fan balanced
Perfmode: No permission for fan handling policy file
```

That was ran as root.

I haven't digged much yet, but I kinda expected this to happen as I don't seem to be able to use fancontrol neither, and didn't yet find a way to control the CPU fan using /sys/ devices yet.

I own an ASUS ROG GL552VW, and just let me know what you'd need to attempt a fix that would make it work on my machine.

Regards!

[perfmode-strace.txt](https://github.com/icebarf/perfmode/files/10210488/perfmode-strace.txt)
[perfmode-sys-devices.txt](https://github.com/icebarf/perfmode/files/10210487/perfmode-sys-devices.txt)

**Comment by icebarf** [comment]
Thank you for higighting the issue. I'll be taking a look at the logs you posted in a bit. Thanks!

**Comment by icebarf** [comment]
Okay, So I've gone through the logs you posted. It seems that your device doesn't have the following files:
`/sys/devices/platform/asus-nb-wmi/throttle_thermal_policy`
and
`/sys/devices/platform/asus-nb-wmi/fan_boost_mode`
which is how perfmode sets the "performance modes" for the laptop series.
In your case, it seems the driver exists and provides the relevant files for LEDs but not the files. This is the first time I have encountered someone who as the `asus_nb_wmi` driver module but is missing some files provided by the driver. Are you sure you did not delete them? or perhaps another tool deleted them somehow. I can only take guesses at this.

One solution that I can think of is that you create those files manually as root and then use perfmode to set the fan modes. And see if you notice any difference physically.

**Comment by shdw** [comment]
> Are you sure you did not delete them? or perhaps another tool deleted them somehow. 

I haven't modified anything yet with the kernel or its modules, I'm using a binary kernel with default configuration.

just checked kernel parameters matching ASUS; they're all turned on a modules
``
CONFIG_HID_ASUS=m
CONFIG_ASUS_LAPTOP=m
CONFIG_ASUS_WIRELESS=m
CONFIG_ASUS_WMI=m
CONFIG_ASUS_NB_WMI=m``

> One solution that I can think of is that you create those files manually as root and then use perfmode to set the fan modes. And see if you notice any difference physically.

Do you mean recompiling kernel manually instead of using the distro's binary kernel?

There's probably a different way to achieve the same results with my ROG series, just haven't figured it out yet.  Any advices on ways to figure it out?

**Comment by icebarf** [comment]
> Do you mean recompiling kernel manually instead of using the distro's binary kernel?

> There's probably a different way to achieve the same results with my ROG series, just haven't figured it out yet. Any advices on ways to figure it out?

No. Just something like this:
```
# touch /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
# touch /sys/devices/platform/asus-nb-wmi/fan_boost_mode
# ./perfmode -fan turbo
```
and see if you notice any difference.

**Comment by icebarf** [comment]
I just peeked at the documentation, It seems the files used by `perfmode` are specific to TUF models of laptops. The other way to control fans on other models seems to be using the following:

for directly controlling the fans, write any unsigned 8-bit value to : `/sys/devices/platform/asus-nb-wmi/hwmon/hwmon[[:print:]]*/pwm1`

for changing fan modes by writing any of the following values:
- `0` for full speed
- `1` for manual
- `2` for automatic
to the file `/sys/devices/platform/asus-nb-wmi/hwmon/hwmon[[:print:]]*/pwm1_enable`
