### ISSUE TITLE
Possibility of Windows Support?

### ISSUE THREAD

**Issue by MirazMac** [icebarf/perfmode#7]
Hello. Thanks for the useful utility. I know for Windows there's Armoury Crate but it's loaded with bloat and consumes a lot of resources. 

Is there any way in future you might release this utility for Windows?
Thanks.

**Comment by rdseed** [comment]
Hi Miraz, unfortunately there are no plans for perfmode to be ported to Windows. Linux is my primary (and only) operating system that I use and I do not have any idea *if* the same functionality is exposed on Windows.

Best of Luck,
Amritpal Singh

**Comment by MirazMac** [comment]
I understand. Thanks for the reply.
