### ISSUE TITLE
perfmode command not found

### ISSUE THREAD

**Issue by Narendira27** [icebarf/perfmode#8]
![Screenshot from 2023-10-15 00-53-55](https://github.com/icebarf/perfmode/assets/41791017/2f7566d1-b359-4eaa-9945-e61bf1475396)

**Comment by icebarf** [comment]
Hi, I've updated the code for an unrelated issue you are facing. You should download/clone the latest version.

Regarding "command-not-found", you need to also run `sudo make install`. Then you can run `perfmode`. The `install` targets puts the compiled binary in PATH.

**Comment by Narendira27** [comment]
Thanks, man, it worked!
