### ISSUE TITLE
Any ways?

### ISSUE THREAD

**Issue by Dorlander** [icebarf/perfmode#9]
Need it for Windows

**Comment by icebarf** [comment]
Windows already has Armoury Crate. Perfmode was targetted for linux.

**Comment by Dorlander** [comment]
I know, but my laptop model Asus Fx705dy dsnt support this program as u say

вс, 5 нояб. 2023 г., 08:56 Amrit ***@***.***>:

**Comment by icebarf** [comment]
Install gentoo. 

ps. Can't help because "windows"
